define({
    "Name": "Navn",
    "Schedule": "Tidsplan",
    "ProcessName": "Prosess",
    "DepartmentName": "Rolle/Avdeling",
    "AssignedUserName": "Ansvarlig",
    "AreaName": "Kontrollområde",
    "StatusName": "Status",
    "FileBrowser": "Filbehandler",

    //Add-Edit form
    "AddNewControlPoint": "Kontrollpunkt - Nytt",
    "Description": "Beskrivelse",
    "Process": "Prosess",
    "Department": "Rolle/Avdeling",
    "AssignedTo": "Ansvarlig",
    "EditControlPoint": "Kontrollpunkt - Rediger",
    "DetailControlPoint": "Kontrollpunkt - Detaljer",
    "CrateControlPoint": "Kontrollpunkt - Skape",
    "Cancel": "Avbryt",
    "Save": "Lagre",
    "Delete": "Slett",
    "NoAttachment": "Ingen vedlegg",
    "Attachments": "Vedlegg",
    "Detail": "Generelt",
    "Specific": "Detaljer",
    "Log": "Logg",
    "Logs": "Loggoppføring(er)",
    "NoLogs": "Ingen loggoppføringer",
    "Attachment": "Vedlegg",
    "PleaseSelectAValidArea": "Velg et gyldig kontrollområde",
    "InvalidValue": "Ugyldig verdi",
    //History
    "ControlPointHistory": "Kontrollpunkt - Historikk",
    "ScheduledDate": "Aktivert",
    "DueDate": "Forfall",
    "CompletedDate": "Signert",
    "ExecutionStatusName": "Status",
    "Close": "Lukk",
    //Page level
    "History": "Historikk",
    "AddNew": "Legg til",

    "Archive": "Arkivert",
    "Duplicate": "Dupliser",
    "ControlPoint": "Kontrollpunkter",
    "Planning": "Plan",
    "DueIn": "Forfall (måneder før periodeslutt) ",
    //"Months": "måneder før periodeslutt",
    "ArchiveConfirmation": "Er du sikker på at du vil arkivere de markerte elementene ?",
    "ArchiveHeader": "Kontrollpunkt - Arkiver",
    "OK": "OK",
    "Yes": "Ja",
    "No": "Ikke",
    "DeleteHeader": "Kontrollpunkt - Slett",
    "DeleteConfirmation": "Er du sikker på at du vil slette dette kontrollpunktet ?",
    // toastr messages
    "MsgControlPointCreated": "Kontrollpunkt opprettet",
    "MsgControlPointEdited": "Kontrollpunkt redigert",
    "MsgControlPointHasBeenDuplicatedWithDefaults": "Kontrollpunkt duplisert",
    "MsgControlPointArchived": "Kontrollpunkt arkivert",
    "MsgControlPointDeleted": "Sletting fullført",
    "MsgErrorOccuredPleaseTryAgain": "En feil oppstod, vennligst oppdater og prøv igjen.",
    "ActiveInactive": "Aktiv/Inaktiv",
    "SelectFiles": "Velg filer ...",

    "StatusToggle": "Bytt status",
    "ControlPointStatusesHaveBeenSwappedSuccessfully": "Statusen for de valgte kontrollpunktene ble byttet",
    "ErrorOccurredPleaseTryAgain": "Feilen oppstod. Vær så snill, prøv på nytt",

    "StartPeriod": "Start periode",
    "ProcessPlaceHolder": "Klikk for å velge prosess",
    "RolePlacehoder": "Klikk for å velge rolle/avdeling",

    "ClientQuestionVisible": "Spør om brudd og relevans?"

});