define({
    "Name": "Name",
    "Schedule": "Schedule",
    "ProcessName": "Process",
    "DepartmentName": "Role / Department",
    "AssignedUserName": "Responsible",
    "AreaName": "Control Area",
    "StatusName": "Status",
    //Add-Edit form:,
    "AddNewControlPoint": "Controlpoint - New",
    "Description": "Description",
    "Process": "Process",
    "Department": "Role / Department",
    "AssignedTo": "Responsible",
    "EditControlPoint": "Controlpoint - Edit",
    "Cancel": "Cancel",
    "Save": "Sign",
    "Attachments": "Attachments",
    "FileBrowser": "File Manager",
    "CrateControlPoint": "Crate - Control Point",

    //History:,
    "ControlPointHistory": "Controlpoint - History",
    "ScheduledDate": "Enabled",
    "DueDate": "Decay",
    "CompletedDate": "Signed",
    "ExecutionStatusName": "Status",
    "Close": "Close",
    //Page level:,
    "History": "History",
    "Add": "Add on",
    "Archive": "Archive",
    "Duplicate": "Duplicate",
    "ControlPoint": "Controlpoint",
    "Planning": "Plan",
    "DueIn": "Due In",
    "Months": "Months before the end of the period",
    "ArchiveConfirmation": "Are you sure you want to archive the selected items?",
    "ArchiveHeader": "Controlpoint - Archive",
    "OK": "OK",
    "Yes": "Yes",
    "No": "No",
    "DeleteHeader": "Controlpoint - Delete",
    "DeleteConfirmation": "Are you sure you want to delete this checkpoint?",
    // toastr messages:,
    "MsgControlPointCreated": "Controlpoint created",
    "MsgControlPointEdited": "Controlpoint edited",
    "MsgControlPointHasBeenDuplicatedWithDefaults": "Controlpoint duplicated",
    "MsgControlPointArchived": "Controlpoint filed",
    "MsgControlPointDeleted": "Deletion completed",
    "MsgErrorOccuredPleaseTryAgain": "An error occurred, please refresh and try again.",
    "ActiveInactive": "Active / Inactive",
    "Archived": "Archived",
    "SelectFiles": "Select Files ...",
    "DueDateRequired": "Maturity Is Required",
    "Export": "Export",
    "Refresh": "Update",
    "Detail": "Detail",
    "Edit": "Editing",
    "ProcessPlaceHolder":"Please click here to select a process",
    "RolePlacehoder":"Please click here to select a role/department"

});