//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoSPA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KendoSPA.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiv.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle undersøkelser.
        /// </summary>
        internal static string AllSurvey {
            get {
                return ResourceManager.GetString("AllSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Årlig.
        /// </summary>
        internal static string Annually {
            get {
                return ResourceManager.GetString("Annually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arkiverte.
        /// </summary>
        internal static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lukket.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferdig i tide.
        /// </summary>
        internal static string CompletedOnTime {
            get {
                return ResourceManager.GetString("CompletedOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullført Forfalt.
        /// </summary>
        internal static string CompletedOverdue {
            get {
                return ResourceManager.GetString("CompletedOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekreftet tap.
        /// </summary>
        internal static string ConfirmedLoss {
            get {
                return ResourceManager.GetString("ConfirmedLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrollpunkter.
        /// </summary>
        internal static string ControlPoint {
            get {
                return ResourceManager.GetString("ControlPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melding.
        /// </summary>
        internal static string ControlPointInstanceCreated {
            get {
                return ResourceManager.GetString("ControlPointInstanceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purring.
        /// </summary>
        internal static string ControlPointInstanceOverDued {
            get {
                return ResourceManager.GetString("ControlPointInstanceOverDued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Påminnelse.
        /// </summary>
        internal static string ControlPointInstancePendingReminder {
            get {
                return ResourceManager.GetString("ControlPointInstancePendingReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato.
        /// </summary>
        internal static string DatePicker {
            get {
                return ResourceManager.GetString("DatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sletting.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullført.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utkast.
        /// </summary>
        internal static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste.
        /// </summary>
        internal static string DropDown {
            get {
                return ResourceManager.GetString("DropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dupliser.
        /// </summary>
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nei.
        /// </summary>
        internal static string FALSE {
            get {
                return ResourceManager.GetString("FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inaktiv.
        /// </summary>
        internal static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hendelser.
        /// </summary>
        internal static string Incident {
            get {
                return ResourceManager.GetString("Incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melding.
        /// </summary>
        internal static string IncidentCreated {
            get {
                return ResourceManager.GetString("IncidentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purring.
        /// </summary>
        internal static string IncidentOverDued {
            get {
                return ResourceManager.GetString("IncidentOverDued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Påminnelse.
        /// </summary>
        internal static string IncidentPendingReminder {
            get {
                return ResourceManager.GetString("IncidentPendingReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / Ref.No :.
        /// </summary>
        internal static string IncidentRef {
            get {
                return ResourceManager.GetString("IncidentRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hendelse registrert.
        /// </summary>
        internal static string IncidentRegistered {
            get {
                return ResourceManager.GetString("IncidentRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncidentSignStatusException-NO.
        /// </summary>
        internal static string IncidentSignStatusException {
            get {
                return ResourceManager.GetString("IncidentSignStatusException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innspill gitt.
        /// </summary>
        internal static string InputGiven {
            get {
                return ResourceManager.GetString("InputGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innspill ikke gitt.
        /// </summary>
        internal static string InputNotGiven {
            get {
                return ResourceManager.GetString("InputNotGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Månedlig.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen tap.
        /// </summary>
        internal static string NoLoss {
            get {
                return ResourceManager.GetString("NoLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjelder ikke.
        /// </summary>
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tall.
        /// </summary>
        internal static string NumericTextbox {
            get {
                return ResourceManager.GetString("NumericTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forfalte.
        /// </summary>
        internal static string Overdue {
            get {
                return ResourceManager.GetString("Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avventer.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potensielt tap.
        /// </summary>
        internal static string PotentialLoss {
            get {
                return ResourceManager.GetString("PotentialLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeidet.
        /// </summary>
        internal static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosjekt.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melding.
        /// </summary>
        internal static string ProjectActivated {
            get {
                return ResourceManager.GetString("ProjectActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purring.
        /// </summary>
        internal static string ProjectOverDued {
            get {
                return ResourceManager.GetString("ProjectOverDued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Påminnelse.
        /// </summary>
        internal static string ProjectPendingReminder {
            get {
                return ResourceManager.GetString("ProjectPendingReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiltak.
        /// </summary>
        internal static string ProjectTask {
            get {
                return ResourceManager.GetString("ProjectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melding.
        /// </summary>
        internal static string ProjectTaskActivated {
            get {
                return ResourceManager.GetString("ProjectTaskActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purring.
        /// </summary>
        internal static string ProjectTaskOverDued {
            get {
                return ResourceManager.GetString("ProjectTaskOverDued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Påminnelse.
        /// </summary>
        internal static string ProjectTaskPendingReminder {
            get {
                return ResourceManager.GetString("ProjectTaskPendingReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisert.
        /// </summary>
        internal static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvartal.
        /// </summary>
        internal static string Quarterly {
            get {
                return ResourceManager.GetString("Quarterly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldt.
        /// </summary>
        internal static string Reviewed {
            get {
                return ResourceManager.GetString("Reviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planlagt.
        /// </summary>
        internal static string Scheduled {
            get {
                return ResourceManager.GetString("Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halvårlig.
        /// </summary>
        internal static string SemiAnnually {
            get {
                return ResourceManager.GetString("SemiAnnually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hendelse opprettet.
        /// </summary>
        internal static string TaskCreated {
            get {
                return ResourceManager.GetString("TaskCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekstområde.
        /// </summary>
        internal static string TextArea {
            get {
                return ResourceManager.GetString("TextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst.
        /// </summary>
        internal static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string TRUE {
            get {
                return ResourceManager.GetString("TRUE", resourceCulture);
            }
        }
    }
}
